In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from itertools import cycle, islice

%matplotlib inline

In [18]:
entrenamiento_df = pd.read_csv('Archivos/entrenamiento_nltk.csv', converters={'text': eval})
train = pd.read_csv('Archivos/train_5_features.csv')

In [19]:
train.head()

,target,longitud_text,cantidad_palabras,keyword_mean,location_mean,numerales
0,1,69,13,0.688525,0.424398,1
1,1,38,7,0.688525,0.424398,0
2,1,133,22,0.688525,0.424398,0
3,1,65,8,0.688525,0.424398,1
4,1,88,16,0.688525,0.424398,2

In [20]:
entrenamiento_df.head()

,id,keyword,location,text,target
0,1,NaN,NaN,"[our, deed, reason, earthquak, may, allah, for...",1
1,4,NaN,NaN,"[forest, fire, near, la, rong, sask, canada]",1
2,5,NaN,NaN,"[all, resid, ask, shelter, place, notifi, offi...",1
3,6,NaN,NaN,"[13, 000, peopl, receiv, wildfir, evacu, order...",1
4,7,NaN,NaN,"[just, got, sent, photo, rubi, alaska, smoke, ...",1

In [21]:
# Agrego feature con la cantidad de palabras relevantes del texto
train['cant_palabras_relevantes'] = entrenamiento_df['text'].agg(lambda x: len(x))

In [22]:
train.head()

,target,longitud_text,cantidad_palabras,keyword_mean,location_mean,numerales,cant_palabras_relevantes
0,1,69,13,0.688525,0.424398,1,8
1,1,38,7,0.688525,0.424398,0,7
2,1,133,22,0.688525,0.424398,0,13
3,1,65,8,0.688525,0.424398,1,8
4,1,88,16,0.688525,0.424398,2,10

In [46]:
# Agreco columnas con las longitudes de la palabra mas larga y la palabra mas corta del texto
train['long_palabra_larga'] = entrenamiento_df['text'].agg(lambda x: max([len(i) for i in x]))
train['long_palabra_corta'] = entrenamiento_df['text'].agg(lambda x: min([len(i) for i in x]))

In [47]:
train.head()

,target,longitud_text,cantidad_palabras,keyword_mean,location_mean,numerales,cant_palabras_relevantes,palabra_mas_larga,long_palabra_larga,long_palabra_corta
0,1,69,13,0.688525,0.424398,1,8,9,9,2
1,1,38,7,0.688525,0.424398,0,7,6,6,2
2,1,133,22,0.688525,0.424398,0,13,7,7,2
3,1,65,8,0.688525,0.424398,1,8,10,10,2
4,1,88,16,0.688525,0.424398,2,10,7,7,3

In [48]:
train['long_palabra_corta'].value_counts()

2     3364
1     2198
3      857
0      687
4      368
5       92
6       33
7        7
8        3
10       2
14       1
9        1
Name: long_palabra_corta, dtype: int64

In [49]:
train.to_csv('Archivos/train_8_features.csv', index=False)

In [50]:
test_df = pd.read_csv('Archivos/test_nltk.csv', converters={'text': eval})
test = pd.read_csv('Archivos/test_5_features.csv')

In [52]:
# Repito las columnas para el archivo test
test['cant_palabras_relevantes'] = test_df['text'].agg(lambda x: len(x))
test['long_palabra_larga'] = test_df['text'].agg(lambda x: max([len(i) for i in x]))
test['long_palabra_corta'] = test_df['text'].agg(lambda x: min([len(i) for i in x]))

In [53]:
test.head()

,longitud_text,cantidad_palabras,keyword_mean,location_mean,numerales,cant_palabras_relevantes,long_palabra_larga,long_palabra_corta
0,34,6,0.688525,0.424398,0,5,7,3
1,64,9,0.688525,0.424398,1,7,9,4
2,96,19,0.688525,0.424398,0,11,6,1
3,40,4,0.688525,0.424398,2,4,9,5
4,45,8,0.688525,0.424398,0,6,8,2

In [54]:
test.to_csv('Archivos/test_8_features.csv', index=False)